In [2]:
import pandas as pd
df = pd.read_csv("Combine Review Data set.csv")[['Destination_link','Review','Sentiment Score']]
df.head(4)

Destination_link                                             Review  \
0              9376  Thank you for help making my honeymoon a memor...   
1              9376  Our guide really made the tour great. The dest...   
2              9376  I really appreciate everything that Travel Tal...   
3              9376  Overall it was such a surreal and fun experien...   

   Sentiment Score  
0                5  
1                5  
2                5  
3                4

In [3]:
df.shape

(7912, 3)

In [4]:
df.isnull().sum()

Destination_link    0
Review              0
Sentiment Score     0
dtype: int64

In [5]:
x = df['Review']
y = df['Sentiment Score']

In [6]:
print(x.shape)
print(y.shape)

(7912,)
(7912,)


## Now we will apply some preprocessing on the x 

In [10]:
x

0       Thank you for help making my honeymoon a memor...
1       Our guide really made the tour great. The dest...
2       I really appreciate everything that Travel Tal...
3       Overall it was such a surreal and fun experien...
4       I really enjoyed me tour it was excellent. I m...
                              ...                        
7907    We did a Blossom Tour with Hunza Explorer and ...
7908    We were a bit anxious about Pakistan before th...
7909    Well designed itinerary to see blossom in Hunz...
7910    We did a Blossom Tour with Hunza Explorer and ...
7911    We were a bit anxious about Pakistan before th...
Name: Review, Length: 7912, dtype: object

## importing libraries for text preprocessing

In [11]:
import nltk
import re
from nltk.corpus import stopwords

In [12]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\seher\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [13]:
from nltk.stem.porter import PorterStemmer

In [14]:
## Creating obj of the porter stemmer
stemmer = PorterStemmer()

# Applying preprocessing on data

- Removing unwanted Characters
- eliminate stop words
- lower case
- Stemming

In [15]:
## for showing the progress bcz it's takes time 
from tqdm import tqdm

In [17]:
corpus = []
for i in tqdm(range(0, len(x))):
    review = re.sub('[^a-zA-Z]', " ", x[i])
    review = review.lower()
    review = review.split()
    
    review = [ stemmer.stem(words) for words in review if not words in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7912/7912 [02:04<00:00, 63.61it/s]


In [19]:
corpus[5]

'one best tour ever join thank travel talk great servic amaz time spent tour tour well organ tour leader deve help inform hotel stay star show'

In [20]:
!pip install tensorflow-gpu

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
conda-repo-cli 1.0.4 requires pathlib, which is not installed.
anaconda-project 0.10.2 requires ruamel-yaml, which is not installed.


  Using cached requests-2.30.0-py3-none-any.whl (62 kB)
  Attempting uninstall: requests
    Found existing installation: requests 2.18.4
    Uninstalling requests-2.18.4:
      Successfully uninstalled requests-2.18.4


In [21]:
import tensorflow as tf

## Creating Embedding layer

In [22]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [51]:
vocab_size = 1000000

## Getting indexes after applying the one hot ecoding using keras

In [52]:
one_hot_rep = [ one_hot(word, vocab_size) for word in corpus]

## Finding the highest len of the review in the corpus

In [55]:
len(one_hot_rep[34])

22

In [56]:
len(one_hot_rep[3400])

24

In [57]:
len(one_hot_rep[5000])

23

In [59]:
max_list = max(one_hot_rep, key=len)

# Print the result
print(len(max_list))

46


In [60]:
lenght = 46
for i in tqdm(range(1, len(corpus))):
    if lenght < len(one_hot_rep[i]):
        lenght = len(one_hot_rep[i])
        print(lenght, " and the index is:" , i)

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7911/7911 [00:00<00:00, 357424.42it/s]


In [62]:
corpus[0]

'thank help make honeymoon memor experi well done travel talk'

In [63]:
lenght

46

### let's find the mean here for the sentence len

In [64]:
sum_len = 0
for i in tqdm(range(0, len(corpus))):
    sum_len = sum_len + len(one_hot_rep[i])

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7912/7912 [00:00<00:00, 506391.18it/s]


In [65]:
sum_len / len(corpus)

17.120070778564205

## So here we considered the max len 130 and the the review above that len will get discarded

In [66]:
length = 130

### Applying pedding to keep the size of the input same that's why we above find the len of the sentence

In [67]:
padding_data = pad_sequences(one_hot_rep, padding = 'post', maxlen = length)

In [68]:
padding_data[35]

array([458739, 400507, 288708, 170460, 525994, 637232, 162668, 199762,
       237668, 738393, 640301, 257049, 400507, 227871, 162668, 880515,
       288708, 705461, 393822, 369239, 233141, 137496, 617824, 466170,
            0,      0,      0,      0,      0,      0,      0,      0,
            0,      0,      0,      0,      0,      0,      0,      0,
            0,      0,      0,      0,      0,      0,      0,      0,
            0,      0,      0,      0,      0,      0,      0,      0,
            0,      0,      0,      0,      0,      0,      0,      0,
            0,      0,      0,      0,      0,      0,      0,      0,
            0,      0,      0,      0,      0,      0,      0,      0,
            0,      0,      0,      0,      0,      0,      0,      0,
            0,      0,      0,      0,      0,      0,      0,      0,
            0,      0,      0,      0,      0,      0,      0,      0,
            0,      0,      0,      0,      0,      0,      0,      0,
      

### Embedding Layer
It performs embedding operations in input layer. It is used to convert positive into dense vectors of fixed size. Its main application is in text analysis. 

### As we get tense vocab, now we need to convert it into the vectors.

### for this, we will be taking each word and than representing it with the number of features (let say we pass the len 8, than each word is represented by 8 different values which are actually the features)

In [80]:
embedding_layer_features = 170

## Using Bidirectional LSTM here

In [70]:
from tensorflow.keras.layers import Bidirectional


In [ ]:
model = Sequential()
model.add(Embedding( input_dim = vocab_size,output_dim = embedding_layer_features, input_length = length))
model.add(Bidirectional(LSTM(200)))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer = "adam", metrics = ['accuracy'])
print(model.summary())

In [76]:
len(padding_data), y.shape

(7912, (7912,))

In [77]:
x = padding_data

## Splitting of the data

In [78]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

## Training of the model

In [ ]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

In [67]:
y_pred=model.predict(X_test)

516/516 [==============================] - 90s 170ms/step


In [68]:
import numpy as np
b=np.where(y_pred > 0.6, 1,0) ##AUC ROC Curve 

In [69]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[7202, 1006],
       [1677, 6615]], dtype=int64)

In [70]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.81      0.88      0.84      8208
           1       0.87      0.80      0.83      8292

    accuracy                           0.84     16500
   macro avg       0.84      0.84      0.84     16500
weighted avg       0.84      0.84      0.84     16500



In [71]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8373939393939394

In [73]:
y_test

sentiment_positive
33553                   1
9427                    1
199                     0
12447                   1
39489                   0
...                   ...
27615                   1
21964                   1
33321                   1
40225                   1
28203                   0

[16500 rows x 1 columns]

In [74]:
y_pred[1]

array([1])